package com.spring.transaction.repository;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.spring.transaction.model.CardType;

/**
 * 
 * @author udaykiran pulipati
 * <p>
 * 	primary key variable type in CardType model is String, 
 * 	but CardTypeRepository extends MongoRepository with primary key type ObjectId.
 * 	So primary key output will be autogenerated of ObjectId type.
 * </p>
 *
 */
@RepositoryRestResource(collectionResourceRel = "cardType", path = "cardType")
public interface CardTypeRepository extends MongoRepository<CardType, ObjectId> {

}
